sudo: required

services:
  - docker

language: python
python:
  - "3.5"

env:
  - DB=postgres
  - DB=mysql
  - DEV=true

install:
  - docker --version && python --version
  - sudo pip install docker-compose
  - sudo pip install python-gitlab
  - ./build.sh
  - docker-compose --version

before_script:
  - sh tests/generate_tests.sh

script:
  - sh tests/test.sh

after_success:
  - sh .travis/deploy_dockerhub.sh

after_script:
   - docker-compose down
