sudo: required

services:
  - docker

language: python

stages:
  - build
  - pretest
  - testing
  - name: deploy
    if: branch = master
    


env:
  - DB=postgres
  - DB=mysql

jobs:
  include:
    - stage: build
      script:
        - docker --version
        - ./build.sh
        - docker images
    - stage: pretest
      script:
        - sudo pip install docker-compose
        - docker-compose --version
        - sh tests/generate_tests.sh
    - stage: testing
      script: sh ./tests/test.sh
    - stage: deploy
      script: sh .travis/deploy_dockerhub.sh
