sudo: required

services:
  - docker

language: python

stages:
  - build
	- pretest
  - test
	- deploy
	  if: branch = master


env:
  - DB=postgres
  - DB=mysql

jobs:
  include:
	  - stage: build
		  script:
			  - docker --version
		    - ./build.sh
				- docker images
		- stage: pretest
		  script:
				- sudo pip install docker-compose
				- docker-compose --version
			  - sh tests/generate_tests.sh
    - stage: test
		  script:
			  - sh tests/test.sh
			after_script:
			  - docker-compose down
		- stage: deploy
		  script:
			  - sh .travis/deploy_dockerhub.sh
