trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps: 
  - task: PythonScript@0
    inputs:
      scriptSource: 'filepath'
      scriptPath: 'build.py'
      arguments: 'stable'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filepath'
      scriptPath: 'test.py'
      arguments: 'stable'
  - task: Bash@3
    inputs:
      filePath: 'tests/test.sh'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '.travis/deploy.py'
