trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    Stable:
      variant: stable
    Rolling:
      variant: rolling


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filepath'
      scriptPath: 'build.py'
      arguments: $[ variables['variant'] ]
  - task: PythonScript@0
    inputs:
      scriptSource: 'filepath'
      scriptPath: 'test.py'
      arguments: $[ variables['variant'] ]
  - task: Bash@3
    inputs:
      filePath: 'tests/test.sh'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '.travis/deploy.py'
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
                   eq(variables['variant'], 'rolling'))
