version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:latest
    container_name: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    depends_on:
    - database
    environment:
    - DATABASE_URL=mysql+pymysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql
    - DATABASE_CLASS=mailman.database.mysql.MySQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    network_mode: "host"


  mailman-web:
    image: maxking/mailman-web:latest
    container_name: mailman-web
    depends_on:
    - database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_URL=mysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql   
    - HYPERKITTY_API_KEY=someapikey
    - SECRET_KEY=thisisaverysecretkey
    - DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
    network_mode: "host"


  database:
    environment:
      MYSQL_DATABASE: mailmandb
      MYSQL_USER: mailman
      MYSQL_PASSWORD: mailmanpass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always
    image: mariadb:10.3
    volumes:
    - /opt/mailman/database:/var/lib/mysql
    network_mode: "host"
