version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.2
    container_name: mailman-core
    restart: on-failure
    volumes:
    - /opt/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@localhost/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    - MM_HOSTNAME=localhost
    - SMTP_HOST=localhost
    - HYPERKITTY_URL=http://localhost:8000/hyerpkitty
    network_mode: "host"


  mailman-web:
    image: maxking/mailman-web:0.2
    container_name: mailman-web
    restart: on-failure
    depends_on:
    - database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@localhost/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    - MAILMAN_REST_URL=http://localhost:8001
    - MAILMAN_HOST_IP=127.0.0.1
    network_mode: "host"

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: on-failure
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    network_mode: "host"
