version: '3.4'

services:
  mailman-core:
    image: mailman-core:0.2
    build:
      context: ./core
    volumes:
    - config:/opt/mailman/
    stop_grace_period: 30s
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey

  mailman-web:
    image: mailman-web:0.2
    build:
      context: ./web
    depends_on:
    - database
    volumes:
    - web-data:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SECRET_KEY=thisisaverysecretkey
    - SERVE_FROM_DOMAIN=mailman.localhost
    - MAILMAN_ADMIN_USER=admin
    - MAILMAN_ADMIN_EMAIL=mailman@civicrm.ca

  mailman-webserver:
    image: mailman-webserver
    build:
      context: ./nginx
    depends_on:
    - mailman-web
    volumes:
#      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - web-data:/opt/mailman-web-data
    ports:
      - "80/tcp"
    labels:
            mailman.domain.container: "${VSITE_MAILMAN_DOMAIN:-mailman.localhost}"
    deploy:
            #      placement:
              #constraints:
#- node.hostname=={VSITE_NODE-$THIS_NODE}
      labels:
        mailman.domain: "{VSITE_DOMAIN}"

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data

volumes:
  config:
  web-data:
