version: '2'

services:
  mailman-core:
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=mysql+pymysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql
    - DATABASE_CLASS=mailman.database.mysql.MySQLDatabase

  mailman-web:
    depends_on:
    - database
    links:
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_URL=mysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql   
    - DYLD_LIBRARY_PATH=/usr/local/mysql/lib/

  database:
    environment:
      MYSQL_DATABASE: mailmandb
      MYSQL_USER: mailman
      MYSQL_PASSWORD: mailmanpass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always
    image: mariadb:10.3
    volumes:
    - /opt/mailman/database:/var/lib/mysql
    networks:
      mailman:
        ipv4_address: 172.19.199.4
